### ISSUE TITLE
🏎 Formula 1 Model

### ISSUE THREAD

**Issue by cricksmaidiene** [cricksmaidiene/leafydex#1]
Given the tire wear, track temperature, etc., determine when to pit during a race and adapt to standings

## Problem

Race strategy plays a huge role in the success of a race. You only get to fuel up at the start of the race and tires can be changed multiple times using different tire compounds. Tires range from those that get you to go faster at a higher wear and tear to those that make you go slower with a low wear and tear. The race strategy, i.e when to pit, when to put the pedal to the medal and when to conserve fuel can be the difference between a few points or zero points for any team on track.

Race strategy is usually a function of the tire degradation, the weather, track temperature, game-theoretic-ideas on when the competition will pit, and the track layout. In the actual race, a lot of data is fed in from the car and other sources to each of the teams' factories where they run multiple models on top of the streamed information to feed tactics back to the track.

We could consider a simplified model that takes in a lesser amount of variables and predicts simpler outcomes such as live ranges on when to pit and recommended settings for the car, etc. This could also be generalized instead to predicting race outcomes (leaderboard) based on historical race data and driver biases.

## Data Availability

* [Kaggle Formula 1 Race Data](https://www.kaggle.com/datasets/cbhavik/formula-1-ml-classifier)
  * Direct tabular data to start making models with
* [Other Kaggle Datasets on F1 data](https://www.kaggle.com/search?q=formula+1)
* [Wikipedia Data on Historical Races](https://en.wikipedia.org/wiki/2020_Hungarian_Grand_Prix#Race_report)
  * This could lend itself to some text-based analysis such as identifying drivers and where they performed well or undeperformed due to a variety of blunders
* Web Scraping some extra race data from the formula1 site or related pages

**Comment by tighub1** [comment]
Weather also, wet or dry tires, or both

**Comment by cricksmaidiene** [comment]
Evaluated a couple of datasets  (at a high level) and added basic notes here: https://github.com/cricksmaidiene/w207_final_project/blob/f1/f1/README.md
