### ISSUE TITLE
🧼 General Model for Domain Specific Data Cleaning

### ISSUE THREAD

**Issue by cricksmaidiene** [cricksmaidiene/leafydex#2]
A model to "magically" clean data based on domain specific schemas. Ex. financial, time series, geospatial, sales, etc

## About

How about creating a python package for data cleaning that can take inputs as dataframes and a domain (like finance / geo / sales, etc) and run some basic cleaning on top of it. Unsure about the kind of ML this would be like  - as it seems more rule-based and lack of training example for something like supervised learning. Unsupervised learning is still an option and we could incorporate a level of reinforcement where it relays back to the user / developer on what a sample of clean data looks like, user makes some small changes, it processes that and carries it forward

## Data Availability

We can use datasets across domains available from kaggle to test this out

**Comment by tighub1** [comment]
This would be amazing but likely too challenging in the timespan. Could take a Domain Specific Languages approach and let ML determine and define a grammar then once you have that can use a utility like yacc to generate. Funny enough I met Martin Fowler once at a conference, he had jsut published a book on DSLs. But yea likely too much work for this.

**Comment by cricksmaidiene** [comment]
Agreed, gonna close this off as way out of scope for the class.
