### ISSUE TITLE
🗺 Predicting Urban Expansion

### ISSUE THREAD

**Issue by cricksmaidiene** [cricksmaidiene/leafydex#3]
Predict if and in what direction an urban area is growing based on Google Earth engine images

## Problem

Use historical images of cities and urban areas to judge the direction in which the urban sprawl is occuring. Use a computer vision model to predict in which direction the sprawl is most likely to continue. Useful for urban planners and governments to allocate resources and zoning for such purposes

## Data availability
* We can use [google earth engine](https://earthengine.google.com/) to feed in image data historically or use the [geemap](https://geemap.org/) python package
* Requesting satellite data from companies like esri is also a viable option under an educational license

## Project Scope is Wide

If we focus our model on a single city (like SF or Berkeley) then we can complement our model with additional data like traffic flow, patterns, human mobility or others to build a more comprehensive model that takes in a number of surrounding and dependent indicators. We can come up with development indices and what the land coverage, land use and land price would be based on a gradient of these attributes across a city

**Comment by tighub1** [comment]
Mix in sales data, general business conditions like parse news on new business ventures, churn rate (how often are businesses failing) etc ... Would be interesting to look at developing an ML of MLs, like each of the sub-problems trained with what ML model is best for that domain then use a super ML to combine the results.

**Comment by cricksmaidiene** [comment]
After reading a couple papers on this topic and watching a talk on how ESRI (Arguably one of the biggest GIS companies out there) was doing this study (listed below) - it seems a bit heavy ended for a w207 project and seems more like a capstone project. This is because there are multiple layers like `land_use`, `traffic`, `current_population`, etc and we have to examine satellite imagery for edge detection on how the urban areas have been growing historically (using something like [Google Earth Engine]() (which is free to use btw))

* [ESRI Talk on predicting urban expansion with ML](https://www.youtube.com/watch?v=gu1bN2c8BrM)
* [MIT Paper on Prediciting Urban Expansion with ML](https://github.com/cricksmaidiene/w207_final_project/files/9725502/SSRN-id3784787.pdf)
* [Monitoring Urban Expansion using ML](https://github.com/cricksmaidiene/w207_final_project/files/9725540/remotesensing-13-04498-v3.pdf)


I was thinking we can probably reduce the variables and keep it simple for predicting urban expansion for this class but since the variables are so tied-in together, they seem to affect each other dramatically and cannot be treated independently. So probably something for Capstone

**Comment by tighub1** [comment]
definitely sounds like a good capstone project. Add in an app for businesses to use to evaluate new prospective locations, maybe even add in an analysis feature such as too many starbucks in the area given the rate and direction of expansion.
