### ISSUE TITLE
🎮 Video Game Economics Optimizer

### ISSUE THREAD

**Issue by cricksmaidiene** [cricksmaidiene/leafydex#4]
Use CV to inform weapon choices, item crafting and heuristics in-game during gameplay

## Problem

A number of role playing games such as [BotW](https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Breath_of_the_Wild), [Witcher 3](https://en.wikipedia.org/wiki/The_Witcher_3:_Wild_Hunt), [Elder Scrolls](https://en.wikipedia.org/wiki/The_Elder_Scrolls), and others all involve some level of crafting (i.e, using ingredients from the game world to create potions, food, etc.) or weapons and so on. BotW has a weapon durability system meaning that you have to optimize which weapons you use on which enemies and if some fights are even worth having

We could build a model that feeds in data from in-game gameplay and performs object detection on enemies and has a catalog of inventory items to make live suggestions on what is recommended to do at each stage. Possible applications in e-sports or e-sport training since these games have been around for a while and their mechanics are rock solid.

## Data Availability

Good question. But will need to check this out a bit deeper

**Comment by tighub1** [comment]
This is pretty cool. Play Clash Royale on my phone a lot and often wonder an optimal character to counter offense or optimal deck combination

**Comment by tighub1** [comment]
would you screen scrape? or use game API ?

**Comment by cricksmaidiene** [comment]
Yeah, data collection for this is gonna be a bit of a pain. Let's deprioritise this as you suggested on slack.
