### ISSUE TITLE
⚽️ Sport Fantasy League Prediction

### ISSUE THREAD

**Issue by cricksmaidiene** [cricksmaidiene/leafydex#5]
For soccer,  basketball or formula1, create an ML model that can predict which players and teams to add to the fantasy portfolio before each game / race.

## Problem

Most major sports have a fantasy league option either maintained by the official sporting authority or made by the community. The idea with a fantasy league is to get sports fans more vested in the game outcome, and also because it's fun. You usually have a budget, and different teams and players are available for a price. The idea is to create a team that you want within the pricing and budget constraints. Once the game begins, the team is locked and you earn points for actual points / events that happen in the live game. Once the actual game is over, you cumulate points in the fantasy team and can go head-to-head with friends / family or otherwise play on a state / national level. 

The pricing of different drivers / players change across the season based on their performance and it's usually the case that you can't use one team across an entire season and have to move players and teams around based on stuff like home turf, historical performance in particular events and so on

We could build a model that creates a portfolio of teams for a fantasy league of any major sport that selects and commits teams to maximize potential points earned. 

![image](https://user-images.githubusercontent.com/32425312/190912838-16ad4ba7-f620-45a0-bb71-bda102e8792d.jpeg)

![maxresdefault](https://user-images.githubusercontent.com/32425312/190912875-99e065ad-f605-4cc1-bb95-fb1174727e15.jpeg)

**Comment by tighub1** [comment]
Similarly Fantasy Football and how to select your best starting lineup each week and which doesn't necessarily match real team lineups.

**Comment by cricksmaidiene** [comment]
Upon taking a closer look at this, we would need to develop web scrapers to fetch the fantasy data. While that could certainly be fun, it does detract from the core idea of this course which is modelling, so would probably take a pass on this one due to data availability
