### ISSUE TITLE
Find the Cheat

### ISSUE THREAD

**Issue by tighub1** [cricksmaidiene/leafydex#6]
Problem:

Talk of cheating in Chess. Develop a pattern recognition model to determine if style of play is unusual for a particular player. Apparently Chess.com is doing something similar and I'm not really sure where we'd get player data. Could take a simpler game like Blackjack where  there is a set of best practices and build a sim to generate simulated data. We could ask whether sim data is acceptable.

**Comment by cricksmaidiene** [comment]
Pretty cool! I can look for some datasets to consider before we have to use synthetic data
