### ISSUE TITLE
Kaggle Competitions Horse Racing Data

### ISSUE THREAD

**Issue by tighub1** [cricksmaidiene/leafydex#7]
Take a look at this one: https://www.kaggle.com/competitions/big-data-derby-2022

Seems like a fitting dataset for the class. Can start a baseline model looking at parameter correlation.

**Comment by tighub1** [comment]
I'll start EDA on this one first since its a recent competition from kaggle and hopefully has good data

**Comment by cricksmaidiene** [comment]
Went through the EDA for this, and it looks pretty decent! The dataset for plant leaves image classification seems arguably a bit more interesting to me though
